services:
  - type: web
    name: rfd-website
    runtime: static
    buildCommand: echo "Static site"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /clip
        destination: /clip.html
